/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "./types";
import { Euler, Group, Object3DEventMap } from "three";
import React from "react";

useGLTF.preload("/models/car_port/Main.gltf");

type Props = {
  scale?: number;
  rotation?: Euler | undefined;
};

export function CarPortModel({
  scale = 2,
  rotation = new Euler(0, -Math.PI, 0),
  ...props
}: Props) {
  const ref = React.useRef<Group<Object3DEventMap>>(null);

  const { nodes, materials } = useGLTF(
    "/models/car_port/Main.gltf",
  ) as GLTFResult;

  return (
    <group
      {...props}
      ref={ref}
      dispose={null}
      scale={scale}
      rotation={rotation}
      position={[20, 3, 15]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_001.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_002.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_003.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_004.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_005.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_006.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_007.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_008.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_009.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_010.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_011.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_012.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_013.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_014.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_015.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_016.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_017.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_018.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_019.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_020.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_021.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_022.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_023.geometry}
        material={materials.WorldGridMaterial}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_024.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_025.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_026.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_027.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_028.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_029.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_030.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_031.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_032.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_033.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_034.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_035.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_036.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_037.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_038.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_039.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_040.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_041.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_042.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_043.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_044.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_045.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_046.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_047.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_048.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_049.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_050.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_051.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_052.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_053.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_054.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_055.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_056.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_057.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_058.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_059.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_060.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_061.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_062.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_063.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_064.geometry}
        material={materials.sorapanel}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_065.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_167.geometry}
        material={materials.metal_Inst1}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_hasira_sousyoku.geometry}
        material={materials.MI_Slate_Stone_tmkmfi2ew_2K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_hasira_sousyoku_001.geometry}
        material={materials.MI_Slate_Stone_tmkmfi2ew_2K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Solid_15.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Solid_393.geometry}
        material={materials.metal_Inst1}
        position={[4.931, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_66.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[-0.015, 0.058, 40.181]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_67.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[9.884, 0.058, 40.181]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_68.geometry}
        material={materials.MI_Sand_Blasted_Steel_shrpcapc_4K}
        position={[4.932, 0.058, 40.181]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_008.geometry}
        material={materials.WorldGridMaterial}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_008.geometry}
        material={materials.WorldGridMaterial}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_008.geometry}
        material={materials.Cable}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_009.geometry}
        material={materials.Cable}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_009.geometry}
        material={materials.plastic_Inst2}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_009.geometry}
        material={materials.plastic_Inst}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_009.geometry}
        material={materials.Cable}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_009.geometry}
        material={materials.Cable}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_009.geometry}
        material={materials.plastic_Inst1}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_009.geometry}
        material={materials.Cable}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_069.geometry}
        material={materials.plastic_Inst}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_001.geometry}
        material={materials.Cable}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_194.geometry}
        material={materials.plastic_Inst}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_195.geometry}
        material={materials.metal_Inst}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_476.geometry}
        material={materials.front_panel}
        position={[4.93, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_9.geometry}
        material={materials.WorldGridMaterial}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_9.geometry}
        material={materials.WorldGridMaterial}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_9.geometry}
        material={materials.Cable}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_10.geometry}
        material={materials.Cable}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_10.geometry}
        material={materials.plastic_Inst2}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_10.geometry}
        material={materials.plastic_Inst}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_10.geometry}
        material={materials.Cable}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_10.geometry}
        material={materials.Cable}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_10.geometry}
        material={materials.plastic_Inst1}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_10.geometry}
        material={materials.Cable}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_70.geometry}
        material={materials.plastic_Inst}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_2.geometry}
        material={materials.Cable}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_196.geometry}
        material={materials.plastic_Inst}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_197.geometry}
        material={materials.metal_Inst}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_477.geometry}
        material={materials.front_panel}
        position={[-0.004, 0.058, 40.183]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_10.geometry}
        material={materials.WorldGridMaterial}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_10.geometry}
        material={materials.WorldGridMaterial}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_10.geometry}
        material={materials.Cable}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_11.geometry}
        material={materials.Cable}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_11.geometry}
        material={materials.plastic_Inst2}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_11.geometry}
        material={materials.plastic_Inst}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_11.geometry}
        material={materials.Cable}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_11.geometry}
        material={materials.Cable}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_11.geometry}
        material={materials.plastic_Inst1}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_11.geometry}
        material={materials.Cable}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_71.geometry}
        material={materials.plastic_Inst}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_3.geometry}
        material={materials.Cable}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_198.geometry}
        material={materials.plastic_Inst}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_199.geometry}
        material={materials.metal_Inst}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_478.geometry}
        material={materials.front_panel}
        position={[9.886, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_11.geometry}
        material={materials.WorldGridMaterial}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_11.geometry}
        material={materials.WorldGridMaterial}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_11.geometry}
        material={materials.Cable}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_12.geometry}
        material={materials.Cable}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_12.geometry}
        material={materials.plastic_Inst2}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_12.geometry}
        material={materials.plastic_Inst}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_12.geometry}
        material={materials.Cable}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_12.geometry}
        material={materials.Cable}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_12.geometry}
        material={materials.plastic_Inst1}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_12.geometry}
        material={materials.Cable}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_72.geometry}
        material={materials.plastic_Inst}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_4.geometry}
        material={materials.Cable}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_200.geometry}
        material={materials.plastic_Inst}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_201.geometry}
        material={materials.metal_Inst}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_479.geometry}
        material={materials.front_panel}
        position={[4.948, 0.058, 40.185]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  );
}
