/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    carport_Extruded_001: THREE.Mesh;
    carport_Extruded_002: THREE.Mesh;
    carport_Extruded_003: THREE.Mesh;
    carport_Extruded_004: THREE.Mesh;
    carport_Extruded_005: THREE.Mesh;
    carport_Extruded_006: THREE.Mesh;
    carport_Extruded_007: THREE.Mesh;
    carport_Extruded_008: THREE.Mesh;
    carport_Extruded_009: THREE.Mesh;
    carport_Extruded_010: THREE.Mesh;
    carport_Extruded_011: THREE.Mesh;
    carport_Extruded_012: THREE.Mesh;
    carport_Extruded_013: THREE.Mesh;
    carport_Extruded_014: THREE.Mesh;
    carport_Extruded_015: THREE.Mesh;
    carport_Extruded_016: THREE.Mesh;
    carport_Extruded_017: THREE.Mesh;
    carport_Extruded_018: THREE.Mesh;
    carport_Extruded_019: THREE.Mesh;
    carport_Extruded_020: THREE.Mesh;
    carport_Extruded_021: THREE.Mesh;
    carport_Extruded_022: THREE.Mesh;
    carport_Extruded_023: THREE.Mesh;
    carport_Extruded_024: THREE.Mesh;
    carport_Extruded_025: THREE.Mesh;
    carport_Extruded_026: THREE.Mesh;
    carport_Extruded_027: THREE.Mesh;
    carport_Extruded_028: THREE.Mesh;
    carport_Extruded_029: THREE.Mesh;
    carport_Extruded_030: THREE.Mesh;
    carport_Extruded_031: THREE.Mesh;
    carport_Extruded_032: THREE.Mesh;
    carport_Extruded_033: THREE.Mesh;
    carport_Extruded_034: THREE.Mesh;
    carport_Extruded_035: THREE.Mesh;
    carport_Extruded_036: THREE.Mesh;
    carport_Extruded_037: THREE.Mesh;
    carport_Extruded_038: THREE.Mesh;
    carport_Extruded_039: THREE.Mesh;
    carport_Extruded_040: THREE.Mesh;
    carport_Extruded_041: THREE.Mesh;
    carport_Extruded_042: THREE.Mesh;
    carport_Extruded_043: THREE.Mesh;
    carport_Extruded_044: THREE.Mesh;
    carport_Extruded_045: THREE.Mesh;
    carport_Extruded_046: THREE.Mesh;
    carport_Extruded_047: THREE.Mesh;
    carport_Extruded_048: THREE.Mesh;
    carport_Extruded_049: THREE.Mesh;
    carport_Extruded_050: THREE.Mesh;
    carport_Extruded_051: THREE.Mesh;
    carport_Extruded_052: THREE.Mesh;
    carport_Extruded_053: THREE.Mesh;
    carport_Extruded_054: THREE.Mesh;
    carport_Extruded_055: THREE.Mesh;
    carport_Extruded_056: THREE.Mesh;
    carport_Extruded_057: THREE.Mesh;
    carport_Extruded_058: THREE.Mesh;
    carport_Extruded_059: THREE.Mesh;
    carport_Extruded_060: THREE.Mesh;
    carport_Extruded_061: THREE.Mesh;
    carport_Extruded_062: THREE.Mesh;
    carport_Extruded_063: THREE.Mesh;
    carport_Extruded_064: THREE.Mesh;
    carport_Extruded_065: THREE.Mesh;
    carport_Extruded_065001: THREE.Mesh;
    carport_Extruded_065002: THREE.Mesh;
    carport_Extruded_065003: THREE.Mesh;
    carport_Extruded_167: THREE.Mesh;
    carport_hasira_sousyoku: THREE.Mesh;
    carport_hasira_sousyoku_001: THREE.Mesh;
    carport_Solid_15: THREE.Mesh;
    carport_Solid_393: THREE.Mesh;
    nozuru_Extruded_069: THREE.Mesh;
    nozuru_Extruded_069001: THREE.Mesh;
    nozuru_Extruded_069002: THREE.Mesh;
    nozuru_Extruded_069003: THREE.Mesh;
    nozuru_Extruded_194: THREE.Mesh;
    nozuru_Extruded_194001: THREE.Mesh;
    nozuru_Extruded_194002: THREE.Mesh;
    nozuru_Extruded_194003: THREE.Mesh;
    nozuru_Extruded_195: THREE.Mesh;
    nozuru_Extruded_195001: THREE.Mesh;
    nozuru_Extruded_195002: THREE.Mesh;
    nozuru_Extruded_195003: THREE.Mesh;
    nozuru_NurbsPath_001: THREE.Mesh;
    nozuru_NurbsPath_001001: THREE.Mesh;
    nozuru_NurbsPath_001002: THREE.Mesh;
    nozuru_NurbsPath_001003: THREE.Mesh;
    nozuru_Solid_439_008: THREE.Mesh;
    nozuru_Solid_439_008001: THREE.Mesh;
    nozuru_Solid_439_008002: THREE.Mesh;
    nozuru_Solid_439_008003: THREE.Mesh;
    nozuru_Solid_446_008: THREE.Mesh;
    nozuru_Solid_446_008001: THREE.Mesh;
    nozuru_Solid_446_008002: THREE.Mesh;
    nozuru_Solid_446_008003: THREE.Mesh;
    nozuru_Solid_447_008: THREE.Mesh;
    nozuru_Solid_447_008001: THREE.Mesh;
    nozuru_Solid_447_008002: THREE.Mesh;
    nozuru_Solid_447_008003: THREE.Mesh;
    nozuru_Solid_476: THREE.Mesh;
    nozuru_Solid_476001: THREE.Mesh;
    nozuru_Solid_476002: THREE.Mesh;
    nozuru_Solid_476003: THREE.Mesh;
    nozuru_VisualModel_Solid_372_009: THREE.Mesh;
    nozuru_VisualModel_Solid_372_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_372_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_372_009003: THREE.Mesh;
    nozuru_VisualModel_Solid_373_009: THREE.Mesh;
    nozuru_VisualModel_Solid_373_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_373_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_373_009003: THREE.Mesh;
    nozuru_VisualModel_Solid_374_009: THREE.Mesh;
    nozuru_VisualModel_Solid_374_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_374_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_374_009003: THREE.Mesh;
    nozuru_VisualModel_Solid_375_009: THREE.Mesh;
    nozuru_VisualModel_Solid_375_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_375_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_375_009003: THREE.Mesh;
    nozuru_VisualModel_Solid_376_009: THREE.Mesh;
    nozuru_VisualModel_Solid_376_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_376_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_376_009003: THREE.Mesh;
    nozuru_VisualModel_Solid_377_009: THREE.Mesh;
    nozuru_VisualModel_Solid_377_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_377_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_377_009003: THREE.Mesh;
    nozuru_VisualModel_Solid_378_009: THREE.Mesh;
    nozuru_VisualModel_Solid_378_009001: THREE.Mesh;
    nozuru_VisualModel_Solid_378_009002: THREE.Mesh;
    nozuru_VisualModel_Solid_378_009003: THREE.Mesh;
  };
  materials: {
    ["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]: THREE.MeshStandardMaterial;
    ["sorapanel.002"]: THREE.MeshStandardMaterial;
    WorldGridMaterial: THREE.MeshStandardMaterial;
    metal_Inst1: THREE.MeshStandardMaterial;
    MI_Slate_Stone_tmkmfi2ew_2K: THREE.MeshStandardMaterial;
    plastic_Inst: THREE.MeshStandardMaterial;
    metal_Inst: THREE.MeshStandardMaterial;
    Cable: THREE.MeshStandardMaterial;
    front_panel: THREE.MeshStandardMaterial;
    plastic_Inst2: THREE.MeshStandardMaterial;
    plastic_Inst1: THREE.MeshStandardMaterial;
  };
};

type Props = {
  scale?: number;
};

function NewCarPort({ scale = 1, ...props }: Props) {
  const { nodes, materials } = useGLTF(
    "/models/new_car_port/new-car-port.gltf",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_001.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_002.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_003.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_004.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_005.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_006.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_007.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_008.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_009.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_010.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_011.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_012.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_013.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_014.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_015.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_016.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_017.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_018.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_019.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_020.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_021.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_022.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_023.geometry}
        material={materials.WorldGridMaterial}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_024.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_025.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_026.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_027.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_028.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_029.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_030.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_031.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_032.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_033.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_034.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_035.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_036.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_037.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_038.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_039.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_040.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_041.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_042.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_043.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_044.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_045.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_046.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_047.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_048.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_049.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_050.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_051.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_052.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_053.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_054.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_055.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_056.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_057.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_058.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_059.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_060.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_061.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_062.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_063.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_064.geometry}
        material={materials["sorapanel.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_065.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_065001.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_065002.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_065003.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Extruded_167.geometry}
        material={materials.metal_Inst1}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_hasira_sousyoku.geometry}
        material={materials.MI_Slate_Stone_tmkmfi2ew_2K}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_hasira_sousyoku_001.geometry}
        material={materials.MI_Slate_Stone_tmkmfi2ew_2K}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Solid_15.geometry}
        material={materials["MI_Sand_Blasted_Steel_shrpcapc_4K.002"]}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.carport_Solid_393.geometry}
        material={materials.metal_Inst1}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_069.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_069001.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_069002.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_069003.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_194.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_194001.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_194002.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_194003.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_195.geometry}
        material={materials.metal_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_195001.geometry}
        material={materials.metal_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_195002.geometry}
        material={materials.metal_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Extruded_195003.geometry}
        material={materials.metal_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_001.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_001001.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_001002.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_NurbsPath_001003.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_008.geometry}
        material={materials.WorldGridMaterial}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_008001.geometry}
        material={materials.WorldGridMaterial}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_008002.geometry}
        material={materials.WorldGridMaterial}
        position={[-0.56, -0.378, -0.527]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={25.314}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_439_008003.geometry}
        material={materials.WorldGridMaterial}
        position={[-0.56, -0.378, -0.527]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={25.314}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_008.geometry}
        material={materials.WorldGridMaterial}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_008001.geometry}
        material={materials.WorldGridMaterial}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_008002.geometry}
        material={materials.WorldGridMaterial}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_446_008003.geometry}
        material={materials.WorldGridMaterial}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_008.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={17.977}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_008001.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={17.977}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_008002.geometry}
        material={materials.Cable}
        position={[-0.092, -0.062, -0.087]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2.591}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_447_008003.geometry}
        material={materials.Cable}
        position={[-0.092, -0.062, -0.087]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2.591}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_476.geometry}
        material={materials.front_panel}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_476001.geometry}
        material={materials.front_panel}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_476002.geometry}
        material={materials.front_panel}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_Solid_476003.geometry}
        material={materials.front_panel}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_009.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_009001.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_009002.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_372_009003.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_009.geometry}
        material={materials.plastic_Inst2}
        position={[-0.56, -0.378, -0.527]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={25.314}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_009001.geometry}
        material={materials.plastic_Inst2}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_009002.geometry}
        material={materials.plastic_Inst2}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_373_009003.geometry}
        material={materials.plastic_Inst2}
        position={[-0.56, -0.378, -0.527]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={25.314}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_009.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_009001.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_009002.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_374_009003.geometry}
        material={materials.plastic_Inst}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_009.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_009001.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_009002.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_375_009003.geometry}
        material={materials.Cable}
        position={[-0.026, -0.018, -0.025]}
        scale={1.497}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_009.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_009001.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_009002.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_376_009003.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_009.geometry}
        material={materials.plastic_Inst1}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_009001.geometry}
        material={materials.plastic_Inst1}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_009002.geometry}
        material={materials.plastic_Inst1}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_377_009003.geometry}
        material={materials.plastic_Inst1}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_009.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_009001.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_009002.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nozuru_VisualModel_Solid_378_009003.geometry}
        material={materials.Cable}
        position={[-1.018, -0.686, -0.958]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={43.814}
      />
    </group>
  );
}

useGLTF.preload("/models/new_car_port/new-car-port.gltf");

export default NewCarPort;
