/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["SM_Tesla-Model-X-P90D-2017004"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_1"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_2"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_3"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_4"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_5"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_6"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_7"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_8"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_9"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_10"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_11"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_12"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_13"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_14"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_15"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_16"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_17"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_18"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_19"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_20"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_21"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_22"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_23"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_24"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_25"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_26"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_27"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_28"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_29"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_30"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_31"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_32"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_33"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_34"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_35"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_36"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_37"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_38"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_39"]: THREE.Mesh;
    ["SM_Tesla-Model-X-P90D-2017004_40"]: THREE.Mesh;
  };
  materials: {
    ["MID_MI_BodyColor_0.004"]: THREE.MeshPhysicalMaterial;
    ["plastic_1.004"]: THREE.MeshStandardMaterial;
    ["glass_2.004"]: THREE.MeshStandardMaterial;
    ["glass_1.004"]: THREE.MeshStandardMaterial;
    ["reflection_1.004"]: THREE.MeshStandardMaterial;
    ["aluminum_3.004"]: THREE.MeshStandardMaterial;
    ["reflection_2.004"]: THREE.MeshStandardMaterial;
    ["cloth_1.004"]: THREE.MeshStandardMaterial;
    ["shadow.004"]: THREE.MeshStandardMaterial;
    ["rubber.004"]: THREE.MeshStandardMaterial;
    ["black_metal.004"]: THREE.MeshStandardMaterial;
    ["aluminum_1.004"]: THREE.MeshPhysicalMaterial;
    ["bottom_plastic.004"]: THREE.MeshPhysicalMaterial;
    ["aluminum_2.004"]: THREE.MeshPhysicalMaterial;
    ["bottom_cover.004"]: THREE.MeshPhysicalMaterial;
    ["bottom_shadow.004"]: THREE.MeshPhysicalMaterial;
    ["plastic_gloss.004"]: THREE.MeshStandardMaterial;
    ["reflection_3.004"]: THREE.MeshPhysicalMaterial;
    ["orange_glass.004"]: THREE.MeshStandardMaterial;
    ["red_glass_3.004"]: THREE.MeshStandardMaterial;
    ["window_simple.004"]: THREE.MeshStandardMaterial;
    ["window_dark.004"]: THREE.MeshStandardMaterial;
    ["brake.004"]: THREE.MeshStandardMaterial;
    ["red_glass_1.004"]: THREE.MeshStandardMaterial;
    ["red_glass_2.004"]: THREE.MeshStandardMaterial;
    ["plastic_2.004"]: THREE.MeshStandardMaterial;
    ["cloth_2.004"]: THREE.MeshStandardMaterial;
    ["plastic_3.004"]: THREE.MeshStandardMaterial;
    ["belt.004"]: THREE.MeshStandardMaterial;
    ["plastic_4.004"]: THREE.MeshStandardMaterial;
    ["lamp.004"]: THREE.MeshStandardMaterial;
    ["plastic_6.004"]: THREE.MeshStandardMaterial;
    ["plastic_5.004"]: THREE.MeshPhysicalMaterial;
    ["display.004"]: THREE.MeshStandardMaterial;
    ["pedals.004"]: THREE.MeshPhysicalMaterial;
    ["metal.004"]: THREE.MeshStandardMaterial;
    ["wheel_rubber.004"]: THREE.MeshPhysicalMaterial;
    ["reflection_4.004"]: THREE.MeshStandardMaterial;
    ["disk.004"]: THREE.MeshStandardMaterial;
    ["brake_disk.004"]: THREE.MeshStandardMaterial;
    ["red_plastic.004"]: THREE.MeshStandardMaterial;
  };
};

type Props = {
  scale?: number;
};

useGLTF.preload("/models/new_car_port/tesla.gltf");

function Tesla({ scale = 1, ...props }: Props) {
  const { nodes, materials } = useGLTF(
    "/models/new_car_port/tesla.gltf",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={scale}>
      <group scale={[0.925, 0.925, 0.945]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004"].geometry}
          material={materials["MID_MI_BodyColor_0.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_1"].geometry}
          material={materials["plastic_1.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_2"].geometry}
          material={materials["glass_2.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_3"].geometry}
          material={materials["glass_1.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_4"].geometry}
          material={materials["reflection_1.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_5"].geometry}
          material={materials["aluminum_3.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_6"].geometry}
          material={materials["reflection_2.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_7"].geometry}
          material={materials["cloth_1.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_8"].geometry}
          material={materials["shadow.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_9"].geometry}
          material={materials["rubber.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_10"].geometry}
          material={materials["black_metal.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_11"].geometry}
          material={materials["aluminum_1.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_12"].geometry}
          material={materials["bottom_plastic.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_13"].geometry}
          material={materials["aluminum_2.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_14"].geometry}
          material={materials["bottom_cover.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_15"].geometry}
          material={materials["bottom_shadow.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_16"].geometry}
          material={materials["plastic_gloss.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_17"].geometry}
          material={materials["reflection_3.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_18"].geometry}
          material={materials["orange_glass.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_19"].geometry}
          material={materials["red_glass_3.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_20"].geometry}
          material={materials["window_simple.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_21"].geometry}
          material={materials["window_dark.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_22"].geometry}
          material={materials["brake.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_23"].geometry}
          material={materials["red_glass_1.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_24"].geometry}
          material={materials["red_glass_2.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_25"].geometry}
          material={materials["plastic_2.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_26"].geometry}
          material={materials["cloth_2.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_27"].geometry}
          material={materials["plastic_3.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_28"].geometry}
          material={materials["belt.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_29"].geometry}
          material={materials["plastic_4.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_30"].geometry}
          material={materials["lamp.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_31"].geometry}
          material={materials["plastic_6.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_32"].geometry}
          material={materials["plastic_5.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_33"].geometry}
          material={materials["display.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_34"].geometry}
          material={materials["pedals.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_35"].geometry}
          material={materials["metal.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_36"].geometry}
          material={materials["wheel_rubber.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_37"].geometry}
          material={materials["reflection_4.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_38"].geometry}
          material={materials["disk.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_39"].geometry}
          material={materials["brake_disk.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["SM_Tesla-Model-X-P90D-2017004_40"].geometry}
          material={materials["red_plastic.004"]}
        />
      </group>
    </group>
  );
}

export default Tesla;
